name: tga
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - expat=2.7.1=h6d0c2b6_0
  - libcxx=19.1.7=haebbb44_3
  - libffi=3.4.4=hecd8cb5_1
  - ncurses=6.5=h923df54_0
  - openssl=3.0.17=hee2dfae_0
  - pip=25.2=pyhc872135_0
  - python=3.11.13=hbff2529_0
  - readline=8.3=h49f2429_0
  - setuptools=78.1.1=py311hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - tk=8.6.15=h3a5a201_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - aws-bedrock-token-generator==1.1.0
      - boto3==1.40.52
      - botocore==1.40.52
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - distro==1.9.0
      - dotenv==0.9.9
      - filelock==3.20.0
      - fsspec==2025.9.0
      - groq==0.32.0
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - idna==3.10
      - jinja2==3.1.6
      - jmespath==1.0.1
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.3
      - packaging==25.0
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pyyaml==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - s3transfer==0.14.0
      - safetensors==0.6.2
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - tokenizers==0.22.1
      - torch==2.2.2
      - tqdm==4.67.1
      - transformers==4.57.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
prefix: /Users/devesh.mishra/miniconda3/envs/tga
